---

- name: cloning repository
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ ansible_user_id }}/.oh-my-zsh"

- name: changing default ZSH theme to Bira
  lineinfile:
    path: /home/{{ ansible_user_id }}/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="bira"'

- name: adding auto suggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: ensure user is using zsh shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
