---

- name: cloning repository
  become: yes
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ".oh-my-zsh"

- name: ensure user is using zsh shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: creating new ~/.zshrc
  copy:
    src: files/zshrc.j2
    dest: ".zshrc"

- name: adding auto suggestions plugin
  become: yes
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ".oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: changing default ZSH Path
  lineinfile:
    path: ".zshrc"
    regexp: '^export ZSH='
    line: 'export ZSH="/home/{{ ansible_user_id }}/.oh-my-zsh"'
